### ISSUE TITLE
Issues Logging In (Quest 2)

### ISSUE THREAD

**Issue by Meolsei** [ReVanced/GmsCore#154]
**Describe the bug**
Normally this would not be an issue for most devices, because they're standard ROMs and not a large VR operating system. The problem in this case is with logging in. When I attempt to log in to my account with GmsCore, it refuses and throws an error like: "There was a problem connecting with Google's servers."

**To Reproduce**
Steps to reproduce the behaviour:
1. On any application, or in the GmsCore settings, find an "Add Account" button.
2. Navigate through the menu and try to log into your Google account as you normally would.
3. See error.

**Expected behaviour**
When attempting to log into your account, the process should be handled properly and you will be logged in.

**System**
Android Version: 12.1
Custom ROM: [Meta Horizon OS](https://en.wikipedia.org/wiki/Meta_Horizon_OS), which is open source and an AOSP fork.

**Additional context**
This issue is to be expected, considering the strange use case. I am trying to log in to YouTube ReVanced.

**Comment by le-dawg** [comment]
Can confirm, same here. 

Using GmsCore v0.3.1.4.240913.

I have noticed that the 2FA prompt is sent twice and that after accpeting the first one the 2nd one expires, suggesting that microG somehow sends two 2FA requests and only listens for the last one that experices, ignoring the successfull 2Fa.

**Comment by oSumAtrIX** [comment]
Check upstream GmsCore, using an emulator for example

**Comment by le-dawg** [comment]
Do I have to use obtainium for that? I got the freshest GmsCore release .. is that not enough?

**Comment by oSumAtrIX** [comment]
You need a full Android emulator with GmsCore installed instead of Google services. Please check online how to do that. The Android and upstream GmsCore documentation is a good start. WSA for Windows is a good emulator. WsaBuilds repo (search on Google) provides easy click to run emulators without Google services. For further support, move to one of our links at https://revanced.app.

**Comment by le-dawg** [comment]
Clarification needed:
 - "upstream GmsCore" aka. micorg/gmscore ?
 - No Meta Quest specific advice on the revanced app, just saying. 
 
 Please confirm:
 - In order to run GmsCore as desired, I need to run a complete Android VM on the Quest AND use the upstream GmsCore?

**Comment by oSumAtrIX** [comment]
Yes to both first points. You'd run a quest VM without google services on your emulator. I don't know if that exists. Check with upstream if Quest is supported by GmsCore. If it is not, neither is this fork.

**Comment by le-dawg** [comment]
Understood. Since some folks seem to have gotten 

According to [this](https://www.reddit.com/r/revancedapp/comments/1emnqdt/installing_youtube_revanced_on_the_meta_quest/) source everything should work out of the box. 

Only the communication between GmsCore and the Google Servers is bricked. I am trying to determine the root cause. 

Issure is not affected by spoof settings in ReVanced.

is there some feature flag or other means to check GmsCore for quest compatibility?

**Comment by oSumAtrIX** [comment]
No, you would need to ask upstream

**Comment by Meolsei** [comment]
I did ask here after asking in GmsCore to see if anybody here could help too. So far, everyone is in the same place. One person suggested we clear storage and cache, which did not help with the main issue. The issue can be found [here](https://github.com/microg/GmsCore/issues/2541) as well.

**Comment by oSumAtrIX** [comment]
In that case the issue needs to be solved upstream. Once fixed, we can merge downstream. Simply let us know here once it is.
