### ISSUE TITLE
docs: README

### ISSUE THREAD

**Issue by kitadai31** [ReVanced/GmsCore#21]
## Suggestion
It would be good to have a own README of this fork.
It would include such things:

- Title
- Purpose of this fork
- Differences from upstream
- Download instructions of this fork

## Motivation
The current README is explaining about upstream microG.
Especially, the "downloads and instructions" link is for upstream, not for this fork. (Download process of this fork is different from the upstream.)
As a result, if users try to read that instructions and apply to this fork, it will fail.

### Expected result
I could get the explain of this fork from README.

### Actual result
I got the explain of upstream microG GmsCore from README.

P.S. If you are already planning this, sorry. I am not trying to rush you.

**Comment by kitadai31** [comment]
@LisoUseInAIKyrios

> Opening to the [release page](https://github.com/ReVanced/GmsCore/releases) is really confusing to someone that doesn't use GitHub.

Isn't it simple enough?

<img height="720" src="https://github.com/ReVanced/GmsCore/assets/90122968/0c89a3bc-29ac-4630-9b5a-fdc31ec97b85">

> It would also be helpful if the Integrations in app 'Gms not found' intent opened a download section of the readme or even better opened a GitHub wiki.

When you turn your eyes to ReVanced Manager's download section of the readme or a Wiki, it just leads users to release page, too.
https://github.com/revanced/revanced-manager#-download
https://github.com/ReVanced/revanced-manager/blob/main/docs/1_installation.md
IMO you don't have to change it.

(Also isn't it should be opened in revanced-integrations repo? (I know you are a team member though))

**Comment by oSumAtrIX** [comment]
The repository is meant to change as little as possible to fulfill its purpose. This conflicts with changing the README. If the issue is that people misinterpret the READMEs links, we should figure out a way to not require the user have to visit it. The release on the other hand allows for a description in markdown and can include a little download image.

**Comment by oSumAtrIX** [comment]
Editing the wiki just to suite YouTube is not the right approach as this fork is treated to be used for any app.

Since the user is never redirected to the repository and instead just to the release, editing that should suffice and also does not require us to edit the wiki. I've manually added a download label to the release, which should suffice for now.
